// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwhijhpkqxwhqdfxffhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3aGlqaHBrcXh3aHFkZnhmZmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MDEzODEsImV4cCI6MjA1MTM3NzM4MX0.3D-MeqvhS3TmD7YOQqHFVjPRBkNbCH_IFfxxLU0k9nQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
